##
# 構成: MySQL + Go Ranking
version: '3'
services:
  mysql:
    build: ./mysql/  #Dockerfileからビルドすることを示す
    ports:
      - "3306:3306" # <-これがないと外からアクセス出来ない
    expose:
      - 3306
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  #初期データ
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    restart: always

  rank:
    build: .
    ports:
      - 11000:11000
    expose:
      - 11000
    volumes:
      - ../:/home/rank/
    restart: always