FROM golang

WORKDIR /home/rank/

#COPY config.json /home/rank/
#COPY main.go /home/rank/
#COPY resources/ /home/rank/resources/
#COPY route_main.go /home/rank/
#COPY template/ /home/rank/template/
#COPY template/ /home/rank/template/
#COPY utils.go /home/rank/
#COPY testgo /home/rank/

COPY ../ /home/rank/

CMD ["cd", "/home/rank/"]

CMD ["ls", "/home/rank"]

#バイナリ実行
CMD ["/home/rank/Intramural-Programming-Rankings"]